FROM 608744602858.dkr.ecr.ap-south-1.amazonaws.com/intellis-ai-scheduler:intellis-17sept-llm-prompt-ztric-feedback-fix-20260918

WORKDIR ${LAMBDA_TASK_ROOT}

COPY . ./

ENV SIMOUR_STORAGE_ROOT=/tmp/intellis_ai_scheduler
ENV INTELLIS_IDEMPOTENCY_ENABLED=true
ENV S3_OUTPUT_PREFIX=generated/vedanjay_ai_intellis

CMD ["intellis_ai_lambda.lambda_handler"]
